name: Regression tests
run-name: ${{ github.actor }} initiated regression tests and linting
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t restful_booker_api_tests .

      - name: Run flake8 in Docker
        run: docker run --rm restful_booker_api_tests flake8

      - name: Run tests in Docker
        run: docker run --rm restful_booker_api_tests pytest -v -s -m regression
